-- Additive administrative-authority contract, revision 1 (2026-09-06).
-- No runtime role receives direct table access. Narrow request finalizers follow.
alter table public.organization_role_assignments
  add constraint organization_role_assignments_org_id_uq unique (organization_id,id);

create table public.company_admin_proposals (
  id uuid primary key check (public.boardagent_is_uuid_v7(id)),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  operation text not null check (operation in ('grant','transfer')),
  issuer_member_id uuid not null,
  issuer_assignment_id uuid not null,
  target_member_id uuid not null,
  issuer_identity_generation bigint not null check (issuer_identity_generation>0),
  target_identity_generation bigint not null check (target_identity_generation>0),
  target_member_version bigint not null check (target_member_version>0),
  reason text not null check (length(reason) between 1 and 2000),
  state text not null default 'pending' check (state in ('pending','accepted','cancelled','declined')),
  row_version bigint not null default 1 check (row_version in (1,2)),
  created_at timestamptz(6) not null default transaction_timestamp(),
  expires_at timestamptz(6) not null,
  creation_consent_id uuid not null references public.consent_records(id) on delete restrict,
  creation_audit_id uuid not null references public.audit_events(id) on delete restrict,
  completed_at timestamptz(6),
  completion_consent_id uuid references public.consent_records(id) on delete restrict,
  completion_audit_id uuid references public.audit_events(id) on delete restrict,
  granted_assignment_id uuid,
  unique (organization_id,id),
  foreign key (organization_id,issuer_member_id) references public.members(organization_id,id) on delete restrict,
  foreign key (organization_id,target_member_id) references public.members(organization_id,id) on delete restrict,
  foreign key (organization_id,issuer_assignment_id) references public.organization_role_assignments(organization_id,id) on delete restrict,
  foreign key (organization_id,granted_assignment_id) references public.organization_role_assignments(organization_id,id) on delete restrict,
  check (issuer_member_id<>target_member_id),
  check (expires_at=created_at+interval '24 hours'),
  check ((state='pending' and row_version=1 and completed_at is null and completion_consent_id is null and completion_audit_id is null)
    or (state<>'pending' and row_version=2 and completed_at is not null and completion_consent_id is not null and completion_audit_id is not null)),
  check ((state='accepted')=(granted_assignment_id is not null)),
  check (completed_at is null or completed_at>=created_at)
);
create index company_admin_proposals_target_idx on public.company_admin_proposals(organization_id,target_member_id,created_at,id);
create index company_admin_proposals_issuer_idx on public.company_admin_proposals(organization_id,issuer_member_id,created_at,id);

create table public.member_admin_delegations (
  id uuid primary key check (public.boardagent_is_uuid_v7(id)),
  organization_id uuid not null,
  board_id uuid not null,
  member_id uuid not null,
  issuer_member_id uuid not null,
  secretary_membership_id uuid not null,
  secretary_membership_version integer not null check (secretary_membership_version>0),
  reason text not null check (length(reason) between 1 and 2000),
  authority_evidence jsonb not null check (jsonb_typeof(authority_evidence)='array' and jsonb_array_length(authority_evidence) between 1 and 8),
  state text not null default 'active' check (state in ('active','revoked')),
  row_version bigint not null default 1 check (row_version in (1,2)),
  created_at timestamptz(6) not null default transaction_timestamp(),
  expires_at timestamptz(6) not null,
  creation_consent_id uuid not null references public.consent_records(id) on delete restrict,
  creation_audit_id uuid not null references public.audit_events(id) on delete restrict,
  revoked_at timestamptz(6),
  revocation_consent_id uuid references public.consent_records(id) on delete restrict,
  revocation_audit_id uuid references public.audit_events(id) on delete restrict,
  unique (organization_id,id),
  foreign key (organization_id,board_id) references public.boards(organization_id,id) on delete restrict,
  foreign key (organization_id,member_id) references public.members(organization_id,id) on delete restrict,
  foreign key (organization_id,issuer_member_id) references public.members(organization_id,id) on delete restrict,
  foreign key (organization_id,board_id,member_id,secretary_membership_id)
    references public.board_memberships(organization_id,board_id,member_id,id) on delete restrict,
  check (expires_at>created_at and expires_at<=created_at+interval '90 days'),
  check ((state='active' and row_version=1 and revoked_at is null and revocation_consent_id is null and revocation_audit_id is null)
    or (state='revoked' and row_version=2 and revoked_at is not null and revocation_consent_id is not null and revocation_audit_id is not null)),
  check (revoked_at is null or revoked_at>=created_at)
);
create index member_admin_delegations_member_idx on public.member_admin_delegations(organization_id,member_id,board_id,created_at,id);

create table public.administrative_authority_changes (
  id uuid primary key check (public.boardagent_is_uuid_v7(id)),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  board_id uuid,
  record_type text not null check (record_type in ('company_admin_proposal','company_admin_assignment','member_admin_delegation')),
  record_id uuid not null check (public.boardagent_is_uuid_v7(record_id)),
  record_version bigint not null check (record_version>0),
  actor_member_id uuid not null,
  action_code text not null check (action_code in ('manage_company_admin','manage_member_admin_delegation')),
  operation text not null check (operation in ('grant','transfer','accept','decline','cancel','revoke')),
  consent_record_id uuid not null references public.consent_records(id) on delete restrict,
  audit_event_id uuid not null unique references public.audit_events(id) on delete restrict,
  canonical_payload bytea not null check (octet_length(canonical_payload) between 2 and 1048576),
  payload_sha256 bytea not null check (public.boardagent_hash_is_sha256(payload_sha256) and payload_sha256=pg_catalog.sha256(canonical_payload)),
  created_at timestamptz(6) not null default transaction_timestamp(),
  unique (organization_id,id),
  unique (organization_id,record_type,record_id,record_version),
  foreign key (organization_id,board_id) references public.boards(organization_id,id) on delete restrict,
  foreign key (organization_id,actor_member_id) references public.members(organization_id,id) on delete restrict
);
create trigger boardagent_immutable before update or delete on public.administrative_authority_changes
  for each row execute function public.boardagent_reject_evidence_mutation();

do $authority_tables$
declare table_name text;
begin
  foreach table_name in array array['company_admin_proposals','member_admin_delegations','administrative_authority_changes'] loop
    execute format('alter table public.%I enable row level security',table_name);
    execute format('alter table public.%I force row level security',table_name);
    execute format('revoke all on public.%I from public,boardagent_server,boardagent_worker',table_name);
    execute format('grant select,insert on public.%I to boardagent_migrator',table_name);
    execute format('grant select on public.%I to boardagent_backup',table_name);
    execute format('create policy boardagent_backup_read on public.%I for select to boardagent_backup using (true)',table_name);
    execute format('create policy boardagent_migrator_administrative_request on public.%I for all to boardagent_migrator using (current_setting(''boardagent.transaction_scope'',true)=''request'' and organization_id=public.boardagent_context_uuid(''boardagent.organization_id'')) with check (current_setting(''boardagent.transaction_scope'',true)=''request'' and organization_id=public.boardagent_context_uuid(''boardagent.organization_id''))',table_name);
  end loop;
end
$authority_tables$;
grant update on public.company_admin_proposals,public.member_admin_delegations to boardagent_migrator;

-- Preserve all original 128 event names and add exactly the eight pinned transitions.
alter table public.audit_events drop constraint audit_events_event_type_check;
alter table public.audit_events add constraint audit_events_event_type_check check (event_type in (
  'context_read',
  'client_registered',
  'client_registration_rejected',
  'oauth_client_blocked',
  'oauth_client_unblocked',
  'token_issued',
  'token_refreshed',
  'token_reuse_detected',
  'session_revoked',
  'enrollment_issued',
  'enrollment_redeemed',
  'enrollment_revoked',
  'member_activated',
  'identity_recovery_started',
  'external_identity_linked',
  'external_identity_unlinked',
  'member_changed',
  'onboarding_stage_created',
  'onboarding_attested',
  'onboarding_stale',
  'authorization_denied',
  'rate_limited',
  'resource_fetch',
  'notice_delivered',
  'document_version_created',
  'document_circulated',
  'document_access_changed',
  'document_archived',
  'document_soft_deleted',
  'recusal_changed',
  'management_submission_created',
  'management_revision_requested',
  'management_revision_replied',
  'management_submission_version_created',
  'management_submission_approved_to_draft',
  'management_submission_rejected',
  'management_question_asked',
  'management_question_answered',
  'management_question_followed_up',
  'secretariat_request_created',
  'secretariat_request_replied',
  'secretariat_request_closed',
  'board_created',
  'board_amended',
  'board_archived',
  'governance_profile_activated',
  'matter_evaluated',
  'ruleset_amended',
  'rule_overridden',
  'stage_created',
  'stage_replaced',
  'elicitation_sent',
  'consent_recorded',
  'consent_rejected',
  'ballot_cast',
  'ballot_superseded',
  'proxy_granted',
  'proxy_revoked',
  'resolution_amended',
  'vote_opened',
  'vote_source_update_pending',
  'vote_source_excluded',
  'vote_closing',
  'vote_closed',
  'vote_cancelled',
  'vote_superseded',
  'vote_replaced',
  'revote_required',
  'certificate_issued',
  'certificate_corrected',
  'meeting_called',
  'meeting_amended',
  'meeting_rsvp_recorded',
  'meeting_attendance_recorded',
  'meeting_attendance_corrected',
  'meeting_completed',
  'meeting_cancelled',
  'transcript_version_created',
  'transcript_secretary_verified',
  'transcript_qna_linked',
  'transcript_turn_challenged',
  'transcript_challenge_resolved',
  'minutes_version_created',
  'minutes_published',
  'minutes_commented',
  'minutes_review_withdrawn',
  'minutes_redline_proposed',
  'minutes_review_dispositioned',
  'minutes_package_corrected',
  'minutes_correction_cycle_created',
  'minutes_action_items_declared',
  'minutes_action_item_draft_superseded',
  'minutes_action_items_activated',
  'minutes_signature_package_issued',
  'minutes_signed',
  'minutes_signature_superseded',
  'minutes_resign_required',
  'minutes_finalized',
  'minutes_cancelled',
  'task_created',
  'task_started',
  'task_evidence_submitted',
  'task_evidence_reviewed',
  'task_completed',
  'task_correction_cycle_created',
  'task_cancelled',
  'proposal_submitted',
  'proposal_withdrawn',
  'proposal_approved_to_draft',
  'proposal_rejected',
  'draft_cancelled',
  'draft_expired',
  'export_requested',
  'export_started',
  'export_performed',
  'export_failed',
  'export_cancelled',
  'export_artifact_deleted',
  'webhook_configured',
  'webhook_secret_rotated',
  'webhook_disabled',
  'webhook_tested',
  'webhook_delivery_attempted',
  'audit_checkpoint_signed',
  'audit_verification_failed',
  'migration_applied',
  'backup_completed',
  'restore_verified',
  'company_admin_proposed',
  'company_admin_proposal_cancelled',
  'company_admin_proposal_declined',
  'company_admin_granted',
  'company_admin_revoked',
  'company_admin_transferred',
  'member_admin_delegation_granted',
  'member_admin_delegation_revoked'
));
