-- Match the declared postgres-text-v1 bytea encoding for redacted rows.
-- Preserve exact scope, grants and stored evidence; only newly generated bytes change.
create or replace function public.boardagent_export_audit_event_rows(candidate_request_id uuid)
returns table(table_rows jsonb,row_count bigint)
language plpgsql
stable
security definer
set search_path=pg_catalog,public,pg_temp
as $$
declare
  request_row public.export_requests%rowtype;
  scope jsonb;
  range_first bigint;
  range_last bigint;
  scope_kind text;
  scope_member_id uuid;
begin
  if current_setting('boardagent.transaction_scope',true) is distinct from 'worker'
     or current_setting('transaction_isolation')<>'repeatable read' then
    raise exception 'audit export reads require a managed repeatable-read worker transaction'
      using errcode='25000';
  end if;
  select request.* into strict request_row
    from public.export_requests as request where request.id=candidate_request_id;
  scope := convert_from(request_row.scope_manifest,'UTF8')::jsonb;
  scope_kind := scope->>'scope';
  scope_member_id := nullif(scope->>'memberId','')::uuid;
  if request_row.state<>'queued'
     or (request_row.export_type='system_data' and not exists (
       select 1 from jsonb_array_elements_text(scope->'dataClasses') as class(value)
        where class.value='audit'
     )) then
    raise exception 'audit component is outside the frozen request scope' using errcode='42501';
  end if;
  if request_row.export_type='audit_chain' then
    range_first := (scope->>'firstSequence')::bigint;
    range_last := (scope->>'lastSequence')::bigint;
  else
    range_first := 1;
    select head.last_sequence into range_last
      from public.audit_chain_head as head where head.singleton_key;
  end if;

  return query
    select coalesce(jsonb_agg(
      case
        when request_row.export_type='audit_chain'
             and (request_row.board_id is null or event.board_id=request_row.board_id)
          then normalized.row_value
        when request_row.export_type='system_data' and scope_kind='organization'
          then normalized.row_value
        when request_row.export_type='system_data' and scope_kind='board'
             and event.board_id=request_row.board_id
          then normalized.row_value
        when request_row.export_type='system_data' and scope_kind='member_portability'
             and (event.actor_member_id=scope_member_id
                  or event.acting_for_member_id=scope_member_id
                  or (event.object_type='member' and event.object_id=scope_member_id))
          then normalized.row_value
        else jsonb_build_object(
          'sequence',event.sequence::text,
          'previous_event_sha256',chr(92)||'x'||encode(event.previous_event_sha256,'hex'),
          'event_sha256',chr(92)||'x'||encode(event.event_sha256,'hex'),
          'redacted','true'
        )
      end order by event.sequence
    ),'[]'::jsonb),count(*)::bigint
      from public.audit_events as event
      cross join lateral (
        select jsonb_object_agg(item.key,item.value order by item.key) as row_value
          from jsonb_each_text(to_jsonb(event)) as item(key,value)
      ) as normalized
     where event.organization_id=request_row.organization_id
       and event.sequence between range_first and range_last;
end
$$;
alter function public.boardagent_export_audit_event_rows(uuid) owner to boardagent_migrator;
revoke all on function public.boardagent_export_audit_event_rows(uuid) from public;
grant execute on function public.boardagent_export_audit_event_rows(uuid) to boardagent_worker;
