// Exact original runtime SQL captured before admission; independent legacy dispatch oracle.
export const ORIGINAL_DOCUMENT_HASH_SQL =
  "select jsonb_build_object(\n           'document_id',document.id,'version_id',version_row.id,'version',version_row.version,\n           'media_type',version_row.media_type,'document_schema',version_row.document_schema,\n           'byte_length',version_row.byte_length,'sha256',encode(version_row.sha256,'hex')\n         ) as view\n         from documents as document\n         join document_versions as version_row on version_row.document_id=document.id\n        where document.id=$1 and version_row.id=$2";
export const ORIGINAL_DOCUMENT_VALIDATION_SQL =
  "select jsonb_build_object(\n           'validation_attempt_id',attempt.id,'board_id',attempt.board_id,\n           'offered_media_type',attempt.offered_media_type,'offered_name',attempt.offered_name,\n           'offered_length',attempt.offered_length::text,\n           'offered_sha256',encode(attempt.offered_sha256,'hex'),\n           'result',attempt.result,'result_code',attempt.result_code,\n           'remediation',attempt.remediation,\n           'accepted_document_version_id',attempt.accepted_document_version_id,\n           'attempted_at',to_char(attempt.attempted_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')\n         ) as view from document_validation_attempts as attempt where attempt.id=$1";
export const ORIGINAL_DOCUMENT_VERSIONS_SQL =
  "select jsonb_build_object(\n           'document_id',version_row.document_id,'version_id',version_row.id,\n           'version',version_row.version,'media_type',version_row.media_type,\n           'document_schema',version_row.document_schema,\n           'byte_length',version_row.byte_length,'sha256',encode(version_row.sha256,'hex'),\n           'created_by',version_row.created_by,\n           'created_at',to_char(version_row.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')\n         ) as item,\n         to_char(version_row.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as cursor_at,\n         version_row.id::text as cursor_id\n         from document_versions as version_row\n         join documents as document on document.id=version_row.document_id\n        where document.id=$1\n          and ($2::timestamptz is null or (version_row.created_at,version_row.id)<($2::timestamptz,$3::uuid))\n        order by version_row.created_at desc,version_row.id desc limit $4";
export const ORIGINAL_DOCUMENT_DOCUMENTS_SQL =
  "select jsonb_build_object(\n         'document_id',document.id,'board_id',document.board_id,'title',document.title,\n         'state',document.state,'version_id',version_row.id,'version',version_row.version,\n         'media_type',version_row.media_type,'document_schema',version_row.document_schema,\n         'byte_length',version_row.byte_length,'sha256',encode(version_row.sha256,'hex'),\n         'row_version',document.row_version::text,\n         'resource_uri','board://' || document.board_id::text || '/documents/' || document.id::text ||\n           '/versions/' || version_row.version::text,\n         'created_at',to_char(document.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')\n       ) as item,\n       to_char(document.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as cursor_at,\n       document.id::text as cursor_id\n       from documents as document\n       join document_versions as version_row on version_row.id=document.current_version_id\n      where document.board_id=$1 and document.state='active'\n        and ($2::timestamptz is null or (document.created_at,document.id)<($2::timestamptz,$3::uuid))\n      order by document.created_at desc,document.id desc limit $4";
