// Exact captured original SQL, independent of the projection helper.
export const ORIGINAL_GOVERNANCE_LIST_SQL = {
  rulesets:
    "select jsonb_build_object(\n           'ruleset_id',ruleset.id,'version',ruleset.version,'state',ruleset.state,\n           'schema_version',ruleset.schema_version,'sha256',encode(ruleset.canonical_sha256,'hex'),\n           'profile_id',ruleset.profile_id,'supersedes_id',ruleset.supersedes_id,\n           'created_at',to_char(ruleset.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')\n         ) as item,\n         to_char(ruleset.created_at at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as cursor_at,\n         ruleset.id::text as cursor_id\n         from rulesets as ruleset where ruleset.board_id=$1\n          and ($2::timestamptz is null or (ruleset.created_at,ruleset.id)<($2::timestamptz,$3::uuid))\n         order by ruleset.created_at desc,ruleset.id desc limit $4",
  templates:
    "select jsonb_build_object(\n           'template_id',template.id,'code',template.code,\n           'approval_rule_id',template.approval_rule_id,\n           'exact_rule',template.exact_rule_payload,\n           'sha256',encode(template.canonical_sha256,'hex')\n         ) as item,template.code as cursor_at,template.id::text as cursor_id\n         from governance_rule_templates as template\n         join boards as board on board.current_governance_profile_id=template.profile_id\n        where board.id=$1 and ($2::text is null or (template.code,template.id)>($2::text,$3::uuid))\n        order by template.code,template.id limit $4",
  matter_types:
    "select jsonb_build_object(\n         'matter_type_id',matter.id,'code',matter.code,'name',matter.name,\n         'strict_fact_schema',matter.strict_fact_schema,\n         'sha256',encode(matter.schema_sha256,'hex')\n       ) as item,matter.code as cursor_at,matter.id::text as cursor_id\n       from matter_types as matter\n       join boards as board on board.current_ruleset_id=matter.ruleset_id\n      where board.id=$1 and ($2::text is null or (matter.code,matter.id)>($2::text,$3::uuid))\n      order by matter.code,matter.id limit $4"
} as const;
